import type { Metadata } from "next"
import "./globals.css"
import { Poppins, Figtree } from "next/font/google"

const fontPrimary = Poppins({
   subsets: ["latin"],
   weight: ["900", "800", "700", "600", "500"],
   variable: "--font-primary",
})

const fontSecondary = Figtree({
   subsets: ["latin"],
   weight: ["300", "400", "500"],
   variable: "--font-secondary",
})

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body
            className={`${fontPrimary.variable} ${fontSecondary.variable} antialiased`}
         >
            {children}
         </body>
      </html>
   )
}
